# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pest"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Michael"]
  s.date = "2012-06-24"
  s.description = "Wrappers to facilitate different classes of probability estimators"
  s.email = "kerinin@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/pest.rb",
    "lib/pest/data_set.rb",
    "lib/pest/data_set/hash.rb",
    "lib/pest/data_set/narray.rb",
    "lib/pest/estimator.rb",
    "lib/pest/estimator/frequency.rb",
    "lib/pest/function.rb",
    "lib/pest/function/entropy.rb",
    "lib/pest/function/probability.rb",
    "lib/pest/variable.rb",
    "lib/pest/version.rb",
    "pest.gemspec",
    "spec/pest/data_set/hash_spec.rb",
    "spec/pest/data_set/narray_spec.rb",
    "spec/pest/data_set_spec.rb",
    "spec/pest/estimator/bernoulli_spec.rb",
    "spec/pest/estimator/frequency_spec.rb",
    "spec/pest/estimator/gaussian_spec.rb",
    "spec/pest/estimator/multinomial_spec.rb",
    "spec/pest/estimator/parzen_spec.rb",
    "spec/pest/estimator/svd_spec.rb",
    "spec/pest/estimator_spec.rb",
    "spec/pest/function/entropy_spec.rb",
    "spec/pest/function/probability_spec.rb",
    "spec/pest/variable_spec.rb",
    "spec/pest_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/kerinin/pest"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Probability Estimation"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<pest>, [">= 0"])
      s.add_runtime_dependency(%q<narray>, [">= 0"])
      s.add_runtime_dependency(%q<uuidtools>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<pest>, [">= 0"])
      s.add_dependency(%q<narray>, [">= 0"])
      s.add_dependency(%q<uuidtools>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<pest>, [">= 0"])
    s.add_dependency(%q<narray>, [">= 0"])
    s.add_dependency(%q<uuidtools>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

